### ISSUE TITLE
Omegle ChatDisconnected Issue (Always keep disconnecting)

### ISSUE THREAD

**Issue by vladimirarevshatyan** [nikkiii/omegle-api-java#6]
First to first if you deploy a library please test,if you did not test and still deploy it then be responsible to what users of you'r library complains about!

After certain ammount of time (no matter messages count) just certain ammount of a time,may be 1 minute,may be 30 seconds,the onChatDisconnected() callback is being triggered automatically and multiple times which causes me to disconnect the current issue due to session disconnecting,meanwhile the opposite side is not disconnected,neither the another side is disonnected as during the callback Trigger,i am still able to receive and send messages,but yet i reckon you done you'r library so poor,that you are triggering the callback in a very wrong way.Take a big NOTICE!

**Comment by nikkiii** [comment]
This library was last maintained 3 years ago, and probably won't be fixed or updated any time soon.

**Comment by vladimirarevshatyan** [comment]
so why don't you review it girl?
